### ISSUE TITLE
Status of Docker containers does not refresh in XenCenter

### ISSUE THREAD

**Issue by porlock** [xenserver/xscontainer#37]
Status of docker containers  in XenCenter does not refresh, when i turn off/on "Container Managment" in VM properties it start to work again for some time, but then it studenlly stops.

My VM is running on CoreOS 1068.10.0 

I see this kind of errors on xscontainer.log

2016-10-12 10:26:05 - [32421] - INFO - execute_ssh will run 'ncat -U /var/run/docker.sock' with stdin 'POST /containers/b8efb11032/start HTTP/1.0' on vm 9b80dc33-50c1-d8b5-4a36-98f77cfcd00d
2016-10-12 10:26:05 - [32421] - INFO - Request 'POST /containers/b8efb11032/start HTTP/1.0

' led to status Not Modified - Container Management Error: The requested operation is currently not possible. Please try again later. (304)
2016-10-12 10:26:05 - [32421] - ERROR - Nobody caught plugin exception: <class 'xscontainer.util.XSContainerException'>
2016-10-12 10:26:05 - [32421] - ERROR - Traceback (most recent call last):

2016-10-12 10:26:05 - [32421] - ERROR -   File "/etc/xapi.d/plugins/xscontainer", line 26, in decorated
    return func(_args, *_kwargs)

2016-10-12 10:26:05 - [32421] - ERROR -   File "/etc/xapi.d/plugins/xscontainer", line 125, in start
    args['container']))

2016-10-12 10:26:05 - [32421] - ERROR -   File "/usr/lib/python2.7/site-packages/xscontainer/docker.py", line 179, in start
    result = _run_container_cmd(session, vmuuid, container, 'start')

2016-10-12 10:26:05 - [32421] - ERROR -   File "/usr/lib/python2.7/site-packages/xscontainer/docker.py", line 174, in _run_container_cmd
    '/containers/%s/%s' % (container, command))

2016-10-12 10:26:05 - [32421] - ERROR -   File "/usr/lib/python2.7/site-packages/xscontainer/docker.py", line 58, in _post_api
    message_error=True)

2016-10-12 10:26:05 - [32421] - ERROR -   File "/usr/lib/python2.7/site-packages/xscontainer/docker.py", line 46, in _interact_with_api
    raise util.XSContainerException(message)

2016-10-12 10:26:05 - [32421] - ERROR - XSContainerException: Request 'POST /containers/b8efb11032/start HTTP/1.0

' led to status Not Modified - Container Management Error: The requested operation is currently not possible. Please try again later. (304)

**Comment by Zhengchai** [comment]
You may need to wait a CoreOS update with Kernel 4.7.4.

**Comment by porlock** [comment]
But sometimes it does ... so it is not permanent bug, are You sure that Kernel 4.7.4 will solve this issue ?

**Comment by simonk83** [comment]
Same issue here, also in Xen Orchestra.
I'm not running CoreOS, I have mostly Debian VM's and the xscontainer plugin pointing to those VM's in XCP-ng.   

Sometimes it shows container status correctly, but more often than not it's incorrect.

![1540114262599-15ef808b-71c3-4c9e-a68e-a7dbe239149b-image](https://user-images.githubusercontent.com/518440/47396560-0f258f80-d777-11e8-8e39-b8a5ee23fd54.png)
![1540114431007-eb4b4821-db61-47e5-aa42-b3ac772d718b-image](https://user-images.githubusercontent.com/518440/47396562-12208000-d777-11e8-9734-29d08d82e10c.png)
